app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
        return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    """
    class that defines the users
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    avatar = db.Column(db.String())
    bio = db.Column(db.String(255))
    password_hashed = db.Column(db.String(255))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    posts = db.relationship('Post', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hashed = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hashed, password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    """
    Class that defines the roles of the users
    """
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return f'User {self.name}'


class Post(db.Model):
    """
    Class that defines the actual blog posts
    """
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    post = db.Column(db.Text)
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship('Comment', backref='post', lazy='dynamic')

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls):
        posts = Post.query.order_by(Post.date_posted.desc()).all()
        return posts


class Comment(db.Model):
    """
    class that defines the comments on pitches
    """

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()


class List(db.Model):
    """
    class that stores followers emails
    """

    __tablename__ = 'lists'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255))

    def save_list(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_emails(cls):
        listed = List.query.order_by(List.id).all()
        return listed

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required


class PostForm(FlaskForm):
    title = StringField('Post title', validators=[Required()])
    post = TextAreaField('Blog post')
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Say something about this', validators=[Required()])
    submit = SubmitField('Submit')


class MailingForm(FlaskForm):
    email = StringField('email',validators=[Required()])
    submit = SubmitField('Join')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()
bootstrap = Bootstrap()
simple = SimpleMDE()
photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):
    """
    creating the app instance to take the specific config and runs the application
    :param config_name:
    :return:
    """

    app = Flask(__name__)

    # creating from config
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Registering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # initialising the app components
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)
    mail.init_app(app)

    # Registering authentication blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User, Post, Comment, List
from flask_login import login_required, current_user
from .forms import PostForm, CommentForm
from .. import db, photos
from ..emails import notification


@main.route('/')
def index():
    """
    Display the landing page
    :return:
    """
    posts = Post.get_posts()
    title = 'Mortus - Welcome to the blog'

    return render_template('index.html', title=title, posts=posts)


@main.route('/new_blog', methods=['GET', 'POST'])
def new_blog():
    """
    Displays the new post page with a markdown form
    :return:
    """
    post_form = PostForm()
    if post_form.validate_on_submit():
        title = post_form.title.data
        post_actual = post_form.post.data
        recepients = List.get_emails()

        new_post = Post(title=title, post=post_actual, user_id=current_user.id)

        new_post.save_post()
        # notification("New blog post", "email/notification", recepients)
        return redirect(url_for('.profile', uname=current_user.username))

    return render_template('new_post.html', post_form=post_form)


@main.route('/user/<uname>')
def profile(uname):
    """
    display user profiles
    :param uname:
    :return:
    """
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    posts = Post.query.filter_by(user_id=user.id).all()

    return render_template("profile/profile.html", user=user, posts=posts)


@main.route('/user/<uname>/update/pic', methods = ['POST'])
@login_required
def update_pic(uname):
    user= User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path=f'photos/{filename}'
        user.avatar = path
        db.session.commit()

    return redirect(url_for('main.profile', uname=uname))


@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(comment=comment, post_id=post_id)

        new_comment.save_comment()

        return redirect(url_for('.post', post_id=post.id))

    comments = Comment.query.filter_by(post_id=post_id).all()

    return render_template('post.html', post=post, post_id=post_id, comment_form=form, comments=comments)

app/templates/base.html
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
{% extends 'bootstrap/base.html'%}

{% block styles %}
    {{ super() }}
<!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

<!-- favicon for the browser-->

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{%extends 'base.html' %}


{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{{ url_for('main.post', post_id=post.id) }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
            </a>
            <p class="post-meta">Posted by {{ post.user_id }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
          </div>
          {% endfor %}
          <hr>
        </div>
      </div>
    </div>

    <hr>



{% endblock %}

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Mortus </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
            </div>

        </div>
    </div>
  </body>
</html>

app/templates/new_post.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
    <div class="col-md-2"></div>
    <div class="col-md-8">
        {{ wtf.quick_form(post_form) }}
        {{ simplemde.load }}
    </div>
    <div class="col-md-2"></div>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<header class="masthead" style="background-image: url('{{ url_for('static', filename='post-bg.jpg') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <span class="meta">Posted by
                {{ post.user_id }}
                on {{ post.date_posted.strftime('%B %d, %Y') }}
                  <hr>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.post|safe }}
                  {% for comment in comments %}
                    {{ comment.comment }}
                        <hr>
                   {% endfor %}
              {{ wtf.quick_form(comment_form) }}
          </div>
        </div>
      </div>
    </article>

    <hr>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>
    {% if user.avatar %}
    <img src="{{url_for('static',filename=user.avatar)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      <a href="{{url_for('main.new_blog')}}">New Post</a>
      {% endif %}

  </div>



  <!--Display posts by profile-->
  <div class="col-md-4">


      <ul>
            {% for post in posts %}
          <li>
              <div class="card">
                  <div class="card-title">
                      <strong>{{post.title}}</strong>
                  </div>
                  <div class="card-body">
                      {{post.post|safe}}
                  </div>
              </div>
          </li>
            {% endfor %}
      </ul>
  </div>
</div>
</div>




{% endblock %}